### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by janpio** [melchor629/chromecaster-gui#8]
![image](https://user-images.githubusercontent.com/183673/46247123-02777b00-c407-11e8-82c6-ad4459d6ceb9.png)

Downloaded from https://melchor629.github.io/chromecaster-gui/ via link https://chromecaster-update-service.herokuapp.com/download

Running Windows 10, newest update locally.

**Comment by janpio** [comment]
Fixed by downloading and installing Bonjour service. 

You might want to add a nicer error message here ;)

**Comment by melchor629** [comment]
Currently I'm trying to remove that dependency because of the problems (like this one). So a nicer error message won't be needed.

Thank you for filling the issue anyway :)
